KeyboardInterrupt detected, shutting down the bot.
CliniCord successfully connected at 23 ms.
Websocket have raised an exception, closing.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/interactions/client/bot.py", line 495, in _login
    await self._websocket.run()
  File "/usr/local/lib/python3.9/dist-packages/interactions/api/gateway/client.py", line 295, in run
    msg = await _receive
  File "/usr/local/lib/python3.9/dist-packages/interactions/api/gateway/client.py", line 981, in __receive_packet
    raise LibraryException(packet.data)
interactions.api.error.LibraryException: 
  Error 4003 | Not authenticated:
  Not authenticated.
  Severity 0.
CliniCord successfully connected at 22 ms.
